# Generated by Django 4.1.5 on 2023-01-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='Img', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
